// cy.get('[data-test=""]')

describe('Navigation on small screens', () => {
	beforeEach(() => {
		cy.viewport('iphone-xr')
	})
	it('toggles and excludes path on home', () => {
		cy.visit('/')
		cy.get('[data-test="cart-button"]')
		cy.get('[data-test="hamburger"]').click()
		cy.get('[data-test="nav-mobile"]').contains('Fechar').should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Home').should('not.be.visible')
		cy.get('[data-test="nav-mobile"]')
			.contains('Homens')
			.should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Mulheres').should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Unisexo').should('be.visible')
		cy.get('[data-test="close-hamburger"]').click()
		cy.get('[data-test="nav-mobile"]').should('not.exist')
	})

	it('toggles and excludes path on homens', () => {
		cy.visit('/homens')
		cy.get('[data-test="cart-button"]')
		cy.get('[data-test="hamburger"]').click()
		cy.get('[data-test="nav-mobile"]').contains('Fechar').should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Home').should('be.visible')
		cy.get('[data-test="nav-mobile"]')
			.contains('Homens')
			.should('be.visible') // Since we use submenus or direct links, let's verify visibility
		cy.get('[data-test="nav-mobile"]').contains('Mulheres').should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Unisexo').should('be.visible')
		cy.get('[data-test="close-hamburger"]').click()
		cy.get('[data-test="nav-mobile"]').should('not.exist')
	})

	it('toggles and excludes path on mulheres', () => {
		cy.visit('/mulheres')
		cy.get('[data-test="cart-button"]')
		cy.get('[data-test="hamburger"]').click()
		cy.get('[data-test="nav-mobile"]').contains('Fechar').should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Home').should('be.visible')
		cy.get('[data-test="nav-mobile"]')
			.contains('Homens')
			.should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Mulheres').should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Unisexo').should('be.visible')
		cy.get('[data-test="close-hamburger"]').click()
		cy.get('[data-test="nav-mobile"]').should('not.exist')
	})

	it('toggles and excludes path on unisexo', () => {
		cy.visit('/unisexo')
		cy.get('[data-test="cart-button"]')
		cy.get('[data-test="hamburger"]').click()
		cy.get('[data-test="nav-mobile"]').contains('Fechar').should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Home').should('be.visible')
		cy.get('[data-test="nav-mobile"]')
			.contains('Homens')
			.should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Mulheres').should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Unisexo').should('be.visible')
		cy.get('[data-test="close-hamburger"]').click()
		cy.get('[data-test="nav-mobile"]').should('not.exist')
	})

	it('toggles and is non dynamic on checkout', () => {
		cy.visit('/checkout')
		cy.get('[data-test="cart-button"]')
		cy.get('[data-test="hamburger"]').click()
		cy.get('[data-test="nav-mobile"]').contains('Fechar').should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Home').should('be.visible')
		cy.get('[data-test="nav-mobile"]')
			.contains('Homens')
			.should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Mulheres').should('be.visible')
		cy.get('[data-test="nav-mobile"]').contains('Unisexo').should('be.visible')
		cy.get('[data-test="close-hamburger"]').click()
		cy.get('[data-test="nav-mobile"]').should('not.exist')
	})
})

describe('Desktop: Cart', () => {
	beforeEach(() => {
		cy.viewport('macbook-11')
	})
	it('bubble invisible on empty cart', () => {
		cy.visit('/')
		cy.get('[data-test="cart-bubble"]').should('not.be.visible')
	})
	it('bubble visible and incrementing when adding items', () => {
		cy.visit('/')
		cy.get('[data-test="nav-homens"]').click()
		// Aguardar o carregamento dos produtos
		cy.get('[data-test^="quick-add-homens-"]').should('have.length.at.least', 1)
		cy.get('[data-test="quick-add-homens-0"]').click()
		cy.get('[data-test="quick-add-homens-0"]').click()
		cy.get('[data-test="quick-add-homens-2"]').click()
		cy.get('[data-test="cart-bubble"]').contains(3)
		cy.get('[data-test="nav-unisexo"]').click()
		cy.get('[data-test^="quick-add-unisexo-"]').should('have.length.at.least', 1)
		cy.get('[data-test="quick-add-unisexo-0"]').click()
		cy.get('[data-test="quick-add-unisexo-0"]').click()
		cy.get('[data-test="cart-bubble"]').contains(5)
	})
	it('toggles on icon button and close button', () => {
		cy.visit('/')
		cy.get('[data-test="cart-modal"]').should('not.exist')
		cy.get('[data-test="cart-button"]').click()
		cy.get('[data-test="cart-modal"]').should('be.visible')
		cy.get('[data-test="cart-close-button"]').click()
		cy.get('[data-test="cart-modal"]').should('not.exist')
	})
	it('bubble invisible when deleting all items', () => {
		cy.visit('/homens')
		cy.get('[data-test^="quick-add-homens-"]').should('have.length.at.least', 1)
		cy.get('[data-test="quick-add-homens-0"]').click()
		cy.get('[data-test="quick-add-homens-0"]').click()
		cy.get('[data-test="quick-add-homens-2"]').click()
		cy.get('[data-test="cart-button"]').click()
		cy.get('[data-test="cart-delete-all"]').click()
		cy.get('[data-test="cart-close-button"]').click()
		cy.get('[data-test="cart-bubble"]').should('not.be.visible')
	})
})
